# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d154124e2fa9f25882516fb40db3bb9f397183e6ac16c6bfc2dc0acfa5e32d30b0bc1fb3fc93d1bc4ddc5cf052444a847807fe219909e33af6eae0720cb32ae

test:
  secret_key_base: 3d904b63b6220228160512d8503b4e04dc0e3de50151cdd390fef427fcd9d0850f95ffcebac7fa4e1337d5ed3675b037d0c1e29c0612e08b36ac82c1fc59d399

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
